- src/urh/controller/SignalFrameController.py
- src/urh/signalprocessing/Signal.py
- src/urh/ui/views/EpicGraphicView.py
> add copy paste to interpretation + refactor Graphic View Class

- setup.py
- src/urh/plugins/InsertSine/InsertSinePlugin.py
- src/urh/plugins/InsertSine/descr.txt
- src/urh/plugins/InsertSine/insert_sine_dialog.ui
- src/urh/plugins/InsertSine/settings.ui
- src/urh/plugins/NetworkSDRInterface/NetworkSDRInterfacePlugin.py
- src/urh/plugins/Plugin.py
- src/urh/signalprocessing/Signal.py
- src/urh/ui/views/EpicGraphicView.py
- src/urh/ui/views/ZoomableGraphicView.py
- src/urh/util/Formatter.py
> Addcustomsine

- src/urh/controller/DecoderWidgetController.py
- src/urh/controller/GeneratorTabController.py
- src/urh/controller/MainController.py
- src/urh/controller/ModulatorDialogController.py
- src/urh/controller/SendRecvDialogController.py
- src/urh/controller/SignalFrameController.py
- src/urh/controller/SignalTabController.py
- src/urh/plugins/InsertSine/InsertSinePlugin.py
- src/urh/plugins/InsertSine/insert_sine_dialog.ui
- src/urh/ui/views/EditableGraphicView.py
- src/urh/ui/views/EpicGraphicView.py
- src/urh/ui/views/LegendGraphicView.py
- src/urh/ui/views/SelectableGraphicView.py
- src/urh/ui/views/ZoomAndDropableGraphicView.py
- src/urh/ui/views/ZoomableGraphicView.py
- tests/test_modulator_gui.py
Reduce code duplication through inheritance
> Refactor graphic view

- src/urh/controller/MainController.py
- src/urh/controller/SignalTabController.py
- src/urh/plugins/InsertSine/InsertSinePlugin.py
- src/urh/ui/ui_tab_interpretation.py
- src/urh/ui/views/EditableGraphicView.py
- src/urh/ui/views/LiveGraphicView.py
- src/urh/ui/views/SelectableGraphicView.py
- src/urh/ui/views/ZoomableGraphicView.py
- tests/test_plugins.py
- ui/tab_interpretation.ui
> Enhance preview of insert sine wave

- src/urh/controller/CompareFrameController.py
- src/urh/ui/views/TextEditProtocolView.py
- tests/test_analysis_tab_GUI.py
- tests/test_signal_tab_GUI.py
add some tests for selection to improve coverage
> Refactor selection

- src/urh/controller/GeneratorTabController.py
- src/urh/controller/MainController.py
- src/urh/controller/SendDialogController.py
- src/urh/controller/SendRecvDialogController.py
- src/urh/controller/SignalFrameController.py
- src/urh/dev/VirtualDevice.py
- src/urh/dev/native/Device.py
- src/urh/dev/native/HackRF.py
- src/urh/dev/native/RTLSDR.py
- src/urh/util/FileOperator.py
- tests/HackRFTests.py
- tests/TestRTLSDR.py
- tests/test_file_operator.py
> HackRF multiprocessing

- src/urh/controller/DecoderWidgetController.py
- src/urh/controller/FuzzingDialogController.py
- src/urh/controller/MessageTypeDialogController.py
- src/urh/controller/ModulatorDialogController.py
- src/urh/controller/OptionsController.py
- src/urh/controller/PluginController.py
- src/urh/controller/ProjectDialogController.py
- src/urh/controller/ProtocolLabelController.py
- src/urh/controller/SendRecvDialogController.py
- src/urh/controller/SignalDetailsController.py
> restore window geometry for dialogs

- src/urh/plugins/RfCat/RfCatPlugin.py
- src/urh/ui/ui_generator.py
- ui/generator.ui
> Rfcat-Plugin now considers configured sending repetitions

- .coveragerc
- src/urh/controller/SignalFrameController.py
- src/urh/signalprocessing/Message.py
- src/urh/signalprocessing/ProtocolAnalyzer.py
- src/urh/ui/views/EpicGraphicView.py
- src/urh/ui/views/SelectableGraphicView.py
- tests/test_send_recv_dialog_gui.py
> Optimize performance of protocol synchronization

- src/urh/controller/CompareFrameController.py
- src/urh/models/GeneratorTableModel.py
- src/urh/models/ProtocolTableModel.py
- src/urh/models/ProtocolTreeItem.py
- src/urh/models/TableModel.py
- src/urh/signalprocessing/Message.py
- src/urh/signalprocessing/ProtocolAnalyzer.py
- src/urh/ui/actions/DeleteBitsAndPauses.py
- src/urh/ui/actions/InsertColumn.py
- src/urh/ui/views/ProtocolTableView.py
- src/urh/ui/views/TableView.py
- tests/test_generator.py
- do not update label ranges in analysis writeable mode
- directly edit decoded bits in writeable mode
- add a zero if space is pressed in writeable analysis or generator
- consider show state in writeable mode
> Fix some issues with writeable mode

- src/urh/controller/DecoderWidgetController.py
- src/urh/signalprocessing/Message.py
- src/urh/signalprocessing/ProtocoLabel.py
- tests/data/protocol_wsp.proto
- tests/test_decoding_gui.py
- tests/test_project_manager.py
> Fix two crashes

- src/urh/controller/GeneratorTabController.py
- src/urh/signalprocessing/ContinuousModulator.py
Prevent spikes for late bursts due to number overflows
> Improve modulation for large protocols

- src/urh/controller/CompareFrameController.py
- src/urh/models/ProtocolLabelListModel.py
- src/urh/models/TableModel.py
- tests/test_analysis_tab_GUI.py
> Show Checksum Status in Tooltip

- src/urh/controller/CompareFrameController.py
- src/urh/models/TableModel.py
- src/urh/signalprocessing/ChecksumLabel.py
- src/urh/signalprocessing/FieldType.py
- src/urh/signalprocessing/MessageType.py
- src/urh/signalprocessing/ProtocoLabel.py
- src/urh/util/ProjectManager.py
- tests/test_generator.py
- tests/test_project_manager.py
> [WIP] improve project file loading

- src/urh/controller/SendDialogController.py
- src/urh/controller/SendRecvDialogController.py
- src/urh/dev/native/AirSpy.py
- src/urh/dev/native/Device.py
- src/urh/dev/native/HackRF.py
- src/urh/dev/native/LimeSDR.py
- src/urh/dev/native/RTLSDR.py
- src/urh/dev/native/SendConfig.py
- src/urh/dev/native/USRP.py
- src/urh/dev/native/lib/hackrf.cpp
- src/urh/dev/native/lib/hackrf.pyx
- tests/HackRFTests.py
> Properly shut down hackrf device

- src/urh/controller/MainController.py
- src/urh/controller/SignalFrameController.py
- src/urh/controller/SignalTabController.py
- src/urh/signalprocessing/Signal.py
- src/urh/util/FileOperator.py
- tests/test_maincontroller_gui.py
> Improve handling of WAV files

- src/urh/controller/MainController.py
- src/urh/controller/SimulatorTabController.py
- src/urh/controller/dialogs/SimulatorDialog.py
- src/urh/controller/widgets/SniffSettingsWidget.py
> Improve simulator useability

- src/urh/models/LabelValueTableModel.py
- src/urh/signalprocessing/ProtocoLabel.py
- src/urh/ui/delegates/ComboBoxDelegate.py
- src/urh/ui/delegates/SectionComboBoxDelegate.py
- src/urh/ui/views/LabelValueTableView.py
- src/urh/util/util.py
- tests/.coveragerc
- tests/test_analysis_tab_GUI.py
> make endianness selectable in order column

- src/urh/controller/CompareFrameController.py
- src/urh/controller/dialogs/ProtocolLabelDialog.py
- src/urh/models/ProtocolTreeItem.py
- src/urh/models/SimulatorMessageFieldModel.py
- src/urh/ui/views/GeneratorTableView.py
- src/urh/ui/views/LabelValueTableView.py
- src/urh/ui/views/SimulatorMessageTableView.py
- src/urh/ui/views/TableView.py
- src/urh/util/util.py
- tests/.coveragerc
- tests/test_simulator_tab_gui.py
> Improve UI

- src/urh/controller/dialogs/OptionsDialog.py
- src/urh/controller/widgets/DeviceSettingsWidget.py
- src/urh/dev/BackendHandler.py
- src/urh/dev/VirtualDevice.py
- src/urh/dev/config.py
- src/urh/dev/native/SoundCard.py
- tests/device/TestSoundCard.py
Add support for SoundCards with PyAudio.
> SoundCard Support

- src/urh/controller/dialogs/OptionsDialog.py
- src/urh/dev/BackendHandler.py
- src/urh/dev/gr/AbstractBaseThread.py
> Fix python2 interpreter settings for Gnuradio backend

- CHANGELOG.md
- src/urh/dev/EndlessSender.py
- src/urh/dev/native/SoundCard.py
> pad short sounds when sending data

- setup.py
- src/urh/dev/native/ExtensionHelper.py
> ensure cython can find config pxi when building with setuptools

- CHANGELOG.md
- src/urh/controller/dialogs/ContinuousSendDialog.py
- src/urh/controller/dialogs/ProtocolSniffDialog.py
- src/urh/controller/dialogs/ReceiveDialog.py
- src/urh/controller/dialogs/SendDialog.py
- src/urh/controller/dialogs/SpectrumDialogController.py
- src/urh/controller/widgets/DeviceSettingsWidget.py
- tests/test_analysis_tab_GUI.py
> Save antenna selection

- CHANGELOG.md
- appveyor.yml
- src/urh/cli/urh_cli.py
- src/urh/ui/views/TableView.py
- tests/cli/test_cli_parsing.py
- tests/data/TestProjectForCLI.xml
> fix hiding for multiple selected rows in analysis

- CHANGELOG.md
- src/urh/cli/urh_cli.py
- src/urh/controller/CompareFrameController.py
- src/urh/models/ParticipantLegendListModel.py
- src/urh/signalprocessing/ProtocolAnalyzer.py
- src/urh/ui/SimulatorScene.py
- fix #497 assign destination address automatically
- show address of participant in legend
- auto assign participant address when clicking analyze in analysis
> Improve bootstrap of simulator messages

- src/urh/models/ParticipantLegendListModel.py
- src/urh/models/ParticipantListModel.py
- src/urh/signalprocessing/Participant.py
> show participant address in analysis model + centralize representation

- .github/ISSUE_TEMPLATE.md
- tests/QtTestCase.py
Address the failing tests on arch linux mentioned in #521
> prevent test failures on arch linux, add cleanup routine

- src/urh/cli/urh_cli.py
> Update URH CLI: Add support for external tools when providing messages (-m)

- CHANGELOG.md
- src/urh/cli/urh_cli.py
- src/urh/dev/config.py
> Enhance settings for RTL-SDR

- .travis.yml
- CHANGELOG.md
- src/urh/ainterpretation/AutoInterpretation.py
- src/urh/controller/CompareFrameController.py
- src/urh/controller/dialogs/DecoderDialog.py
- src/urh/signalprocessing/Encoding.py
- src/urh/util/ProjectManager.py
- tests/test_protocol_sniffer.py
* fix bug when combining de whitening with external programs
* remove decodings.txt for projects, save it in project file
> Bugfix loading decodings and centralized place for decodings

- CHANGELOG.md
- src/urh/controller/MainController.py
- src/urh/models/GeneratorTableModel.py
- src/urh/models/SimulatorMessageFieldModel.py
- src/urh/signalprocessing/ProtocolAnalyzerContainer.py
- src/urh/simulator/SimulatorConfiguration.py
- src/urh/ui/views/GeneratorTableView.py
- do not delete messages in simulator when participant was deleted
- correctly remove checksum property from simulator label when custom name was entered
- allow duplication of multiple lines in generator
> Ergonomic improvements

- CHANGELOG.md
- appveyor.yml
- data/build_cx.py
> Do not add URH to autostart on windows

- CHANGELOG.md
- src/urh/controller/widgets/SignalFrame.py
- src/urh/ui/views/ZoomableGraphicView.py
> keep yscale on view change and on save

- CHANGELOG.md
- appveyor.yml
- src/urh/dev/BackendHandler.py
- src/urh/dev/VirtualDevice.py
- src/urh/dev/config.py
- src/urh/dev/native/ExtensionHelper.py
- src/urh/dev/native/PlutoSDR.py
- src/urh/dev/native/lib/cplutosdr.pxd
- src/urh/dev/native/lib/plutosdr.pyx
- tests/device/TestPlutoSDR.py
- tests/test_util.py
This PR adds native support for Adalm PlutoSDR and fix #393.
> Add native support for PlutoSDR

- src/urh/dev/gr/SpectrumThread.py
> fix crash for spectrum analyzer with GR backend

- data/azure-pipelines.yml
- data/build_cx.py
- data/requirements.txt
- tests/test_simulator.py
- tests/test_simulator_tab_gui.py
Adds a ``` urh_debug.exe ``` to installation directory in order to debug MSI builds better on Windows.
> Add debug build for windows

- src/urh/ainterpretation/AutoInterpretation.py
- src/urh/controller/widgets/SignalFrame.py
- src/urh/cythonext/auto_interpretation.pyx
- src/urh/signalprocessing/Signal.py
- add user feedback if auto interpretation fails
- remove MAX_MESSAGE_SAMPLES threshold
> Improve Auto Interpretation

- data/azure-pipelines.yml
- data/requirements.txt
> fix CI for linux

- data/requirements.txt
- src/urh/dev/config.py
> increase frequency range of PlutoSDR

- README.md
Add repology badge to Readme. Fix #687 .
> add repology badge

- src/urh/dev/gr/AbstractBaseThread.py
- src/urh/dev/gr/scripts/InputHandlerThread.py
- src/urh/dev/gr/scripts/hackrf_recv.py
- src/urh/util/Errors.py
Did a quick search for these. If I spot any others I'll update them as well.
> UI: Updated capitalization of GNU Radio

- src/urh/plugins/MessageBreak/MessageBreakAction.py
- tests/test_plugins.py
> fix message break plugin (#739)

- setup.py
- src/urh/dev/native/ExtensionHelper.py
it can lead to errors on certain environments (#761)
> remove parallelization in ExtensionHelper.py

- data/azure-pipelines.yml
- data/pyinstaller_helper.py
> add retina support on macOS

- data/requirements.txt
- src/urh/signalprocessing/Encoding.py
- src/urh/util/ProjectManager.py
Remove NRZ-I to prevent mixing with NRZ + Invert, clarify names.
> Remove NRZ-I to prevent mixing with NRZ + Invert, clarify names.

- src/urh/signalprocessing/FieldType.py
> Use ElementTree instead of deprecated cElementTree.

- data/generate_ui.py
- src/urh/dev/gr/scripts/__create_gr_script.py
- src/urh/dev/native/PlutoSDR.py
- tests/TestInstallation.py
> Fix deprecation warnings due to invalid escape sequences.

- src/urh/ainterpretation/AutoInterpretation.py
- src/urh/cythonext/auto_interpretation.pyx
- tests/auto_interpretation/test_bit_length_detection.py
> Improve Auto Interpretation Performance

- src/urh/cythonext/auto_interpretation.pyx
> fix overflow in AutoInterpretation for certain signals

- data/build_snap.sh
> add desktop entry to snap

- data/urh.desktop
add category HamRadio to desktop file, fix #888
> add category HamRadio to desktop file

- data/azure-pipelines.yml
- src/urh/signalprocessing/Modulator.py
- src/urh/simulator/Simulator.py
> Simulation fix: use sending device dtype for modulation

- src/urh/ui/views/SelectableGraphicView.py
Variable type mismatch, maybe due to PyQt update? Thanks to nospam2000!
> Variable type mismatch, fix #937

- data/pyinstaller_helper.py
This fixes #864 .  Thanks to @gramss for the research work!
> Fix microphone access for macOS DMG

- src/urh/cythonext/util.pyx
- src/urh/signalprocessing/IQArray.py
> get magnitudes in cython for less memory consumption

- src/urh/dev/config.py
> set BladeRF min sample rate to 520.834 kHz

- src/urh/dev/native/ExtensionHelper.py
> Fix API check on macOS

- src/urh/controller/widgets/SignalFrame.py
> Refresh protocol view also when hidden

- src/urh/controller/widgets/SignalFrame.py
> Keep Y-Scale when showing/hiding demodulated view

- src/urh/dev/BackendHandler.py
- src/urh/dev/VirtualDevice.py
- src/urh/dev/config.py
- src/urh/dev/native/Rad1o.py
- src/urh/signalprocessing/Filter.py
- src/urh/signalprocessing/Spectrogram.py
- tests/device/Rad1oTests.py
Add support for rad1o SDR (like HackRF but without bias_tee)
(fix #1019)
> Add rad1o support

- src/urh/dev/config.py
- src/urh/dev/native/RTLSDR.py
- src/urh/dev/native/lib/crtlsdr.pxd
- src/urh/dev/native/lib/rtlsdr.pyx
Update RTLSDR.py
Update rtlsdr.pyx
Update crtlsdr.pxd
Update config.py
> Bias-T checkbox for RTL-SDR device settings screen #2

- data/ui/main.ui
- src/urh/controller/MainController.py
- src/urh/ui/ui_main.py
> Add exit action and new menu for recent files

- data/requirements.txt
- setup.py
- src/urh/awre/FormatFinder.py
Fix type problem with numpy2.
Drop support for numpy1 to simplify testing.
fixes #1149
> Feat!: use numpy2
