jopohl/urh

- src/urh/ui/delegates/CheckBoxDelegate.py
- src/urh/ui/delegates/ComboBoxDelegate.py
- src/urh/ui/delegates/SpinBoxDelegate.py
> enhance delegates

- src/urh/controller/CompareFrameController.py
- src/urh/signalprocessing/ProtocolAnalyzer.py
- src/urh/util/ProjectManager.py
- tests/test_project_manager.py
This PR fixes a bug where participants do not get assigned properly to previously hidden messages, when loading a project.
> Bugfix for participant assignment when loading project with hidden messages

- src/urh/controller/SignalFrameController.py
- src/urh/signalprocessing/Filter.py
- src/urh/ui/views/SpectrogramGraphicView.py
- tests/test_spectrogram.py
This PR removes the brick wall filter, as it has a bad performance and can produce undesired results, as stated [here](https://dsp.stackexchange.com/questions/6220/why-is-it-a-bad-idea-to-filter-by-zeroing-out-fft-bins).
The original issue #344 is now fixed in a different way with a20ddb1d33c9c7e7d7a369cec90ff71af4587281, so the original need for the brickwall filter is not present anymore.
> remove brick wall filter

- src/urh/signalprocessing/Modulator.py
``` np.exp ``` overflows for values > 300000  ([see here](https://stackoverflow.com/questions/22729223/how-to-calculate-expx-for-really-big-integers-in-python)), so use sin and cos for modulation
> fix overflow error when modulating very long messages

- src/urh/controller/CompareFrameController.py
- tests/test_simulator_tab_gui.py
- tests/test_text_edit_protocol_view.py
When creating a new label in Analysis the initial name for the label is now based on the configured field type. So by default URH now initially names the labels "preamble", "synchronization", "length", ...
> improve initial label types when creating new ones

- src/urh/controller/widgets/SignalFrame.py
- src/urh/signalprocessing/Spectrogram.py
- src/urh/ui/views/EditableGraphicView.py
- src/urh/ui/views/SpectrogramGraphicView.py
- src/urh/util/FileOperator.py
- tests/.coveragerc
- tests/test_signal_tab_GUI.py
- tests/test_simulator.py
This PR allows to export demodulated view and spectrogram in the respective context menus of the views.
> Add export features

- src/urh/controller/CompareFrameController.py
Fix toggling of label visibilty when using mark differences for overlapping labels of different message types. See [this comment](https://github.com/jopohl/urh/issues/451#issuecomment-392908186) for a more detailed explanation.
> fix faulty label visibility behaviour described in #451

- src/urh/simulator/Simulator.py
- src/urh/ui/views/SimulatorGraphicsView.py
- tests/test_simulator.py
Now a pause for a message can be configured in simulator flowgraph via right click on a message.
fix #477
> make message pause configurable in simulator

- .travis.yml
- CHANGELOG.md
- appveyor.yml
- data/requirements.txt
- src/urh/controller/CompareFrameController.py
- src/urh/controller/MainController.py
- src/urh/signalprocessing/ProtocolAnalyzer.py
- src/urh/util/FileOperator.py
- tests/test_protocol_analyzer.py
This PR aims to fix #487 . Protocols can now be saved in binary format (``` .bin ``` from Analysis via the save button:
Vice versa, loading a ``` .bin ``` protocol is possible via the load button right next to the save button or using File -> Open.
> allow save and load of binary protocols

- appveyor.yml
- src/urh/dev/native/lib/csdrplay.pxd
- src/urh/dev/native/lib/sdrplay.pyx
The signature for "mir_sdr_StreamCallback_t" is changed in the latest SDRPlay API.
This breaks the compiling (on file "src/urh/dev/native/lib/sdrplay.cpp:3856")
One argument is added before the latest arg of the callback.
Latest SDRPlay API spec is available here: https://www.sdrplay.com/docs/SDRplay_SDR_API_Specification.pdf
By the way, here I am talking about API 2.x series. SDRPlay is working on the 3.0 API which has a different design (https://www.sdrplay.com/community/viewtopic.php?f=6&t=3345)
> Update SDRPlay native plugin

- CHANGELOG.md
- src/urh/signalprocessing/Message.py
- src/urh/signalprocessing/ProtocolAnalyzer.py
> also consider participant address (next to RSSI) when auto assigning

- CHANGELOG.md
- src/urh/controller/dialogs/ProtocolSniffDialog.py
- src/urh/controller/dialogs/SendRecvDialog.py
- src/urh/controller/dialogs/SpectrumDialogController.py
- tests/test_filter.py
> do not disable clear button

- CHANGELOG.md
- src/urh/models/TableModel.py
fix #543 
So wen can search e.g. for "CAFE" as well as for "cafe"
> ignore case for hex search 

- CHANGELOG.md
- src/urh/ui/views/TableView.py
This PR adds font size zoom to all tables (Analysis/Generator/Simulator). This is especially helpful when dealing with longer messages, as presented in the following example.
You can get a birds-eye-perspective and can see labels at a glance.
Zoom is accessible in the table's __context menu__ and, additionally, with the default zoom shortcuts of your OS. Normally these are:
- __Zoom in__: ``` CTRL ``` + ``` + ```
- __Zoom out__: ``` CTRL ``` + ``` - ```
- __Reset zoom__: ``` CTRL ``` + ``` 0 ```
> Enable zooming font size of table

- CHANGELOG.md
- src/urh/dev/config.py
- src/urh/dev/native/Device.py
- src/urh/dev/native/RTLSDR.py
- src/urh/dev/native/RTLSDRTCP.py
- src/urh/dev/native/lib/rtlsdr.pyx
This PR aims to fix #565. Now all possible gains for all possible RTL-SDRs are supported and the gains are corrected via a call to ```get_tuner_gains``` if needed.
> allow more gains for rtlsdr

- CHANGELOG.md
- src/urh/controller/widgets/SignalFrame.py
> show save button when action on saved signal gets undone

- src/urh/signalprocessing/Signal.py
- src/urh/util/FileOperator.py
Adds the popular .cu8 and .cs8 file name extensions as alias to .complex16u and .complex16s when opening files.
> Add .cu8 .cs8 format alias

- src/urh/ainterpretation/AutoInterpretation.py
If a signal has segments with zero variance i.e. constant lines,
the center detection crashes because the histogram can not be created.
This fix catches the ZeroDivision error and returns None in that case.
> fix center detection crash on special signals (fix #615)

- src/urh/controller/CompareFrameController.py
Pressing the checkboxes "Mark diffs in protocol", "Show only diffs in protocol" or "Show only labels in protocol" in the Analysis tab would crash the app if no rows are available.
Traceback (most recent call last):
File "/urh/src/urh/controller/CompareFrameController.py", line 1398, in on_ref_index_changed
self.protocol_model.refindex = (new_ref_index + hide_correction) % self.protocol_model.row_count
ZeroDivisionError: integer division or modulo by zero
> Fix crash when showing diff of empty protocol

- src/urh/dev/native/ExtensionHelper.py
This checks for the existence of Macports-specific library and include paths and adds them to the compiler flags, so that the native modules detect SDR libraries as expected.
> Add compatibility with Macports

- data/ui/advanced_modulation_settings.ui
- src/urh/controller/widgets/SignalFrame.py
- src/urh/ui/ui_advanced_modulation_settings.py
This fixes an error where the message divisor length was not applied correctly, when configured in the dialog. This furthermore increases the maximum for the divisor length and is therefore a fix #638 .
> fix error with message length divisor

- src/urh/dev/native/ExtensionHelper.py
- tests/test_util.py
In case the automatic API check fails, give users a backup strategy. This PR adds environment variables set API version explicitly. Currently these two are supported:
- BLADERF_API_VERSION
- SDRPLAY_API_VERSION 
Example: ``` SDRPLAY_API_VERSION=2.13 python src/urh/cythonext/build.py ```
> add environment variables to set API version explicitly

- data/azure-pipelines.yml
- src/urh/signalprocessing/MessageType.py
> consider checksum label in copy operation

- src/urh/awre/FormatFinder.py
The auto created "checksum" field/label is initialized with a list with a single tuple for data ranges, which causes URH to crash if the auto guessed range is modified at any point later via CheckSum widget. 
The `__data_ranges` should be `list[list[int, int]]`
Fixes #840
> Use list for checksum data_ranges

- src/urh/controller/widgets/DeviceSettingsWidget.py
- src/urh/dev/config.py
- src/urh/dev/native/BladeRF.py
- src/urh/dev/native/lib/bladerf.pyx
- src/urh/dev/native/lib/cbladerf.pxd
This tool is insanely amazing =) congrats on all the effort to pull all this off like a pro. 
This PR implements a feature that is was requested way back (#703) however, sadly at my lab I only have bladeRF v1 generation. The implementation should work setting up both bias tee on rx and tx side. 
Being said that, @jopohl there is any chance that you could have both bias tee module to test this locally at your lab? 
fix #703
> add bias tee check box on device settings

- src/urh/signalprocessing/Signal.py
When using "Create signal from selection" feature, the newly created
signal does not retain sample rate of the original so all the time of
the selection is computed wrong which is very confusing to the user.
This simple patch makes sure the sample_rate of the original Signal is
copied to the newly created one which fixes the problem.
> Signal: retain the sample_rate on create_new

- src/urh/dev/native/lib/hackrf.pyx
The HackRF device has a freeze-bug when stopping sending or receiving data. As a workaround, there is a 0.2 second timeout in hackrf.pyx.
As far as I can tell, this timeout is only required in `stop_rx_mode` and `stop_tx_mode`. The additional timeouts in the `set_*` methods are an issue because they cause a combined delay of one complete second whenever something is supposed to be sent (e. g. using cli).
I have been running the following code without issues for a while in an application, that sends some data every couple of minutes.
~~~~
hackrf.TIMEOUT = 0
hackrf.set_freq(self.args.frequency)
hackrf.set_sample_rate(self.args.sample_rate)
hackrf.set_baseband_filter_bandwidth(bandwidth)
hackrf.set_rf_gain(gain)
hackrf.set_if_tx_gain(if_gain)
hackrf.TIMEOUT = 0.2
~~~~
I did some manual …
> remove HackRF anti-freeze timeouts in places that do not require them

- src/urh/plugins/RfCat/RfCatPlugin.py
> add b before data string

- src/urh/dev/native/ExtensionHelper.py
> MacOS: Add default include dir during installation

- src/urh/signalprocessing/Encoding.py
Hi,
I had an issue while trying to fuzz a remote control switch, despite successful decoding.
Basically, the raw signal gets perfectly decoded by a 'Remove Carrier' function with a `0_0_0_0_0_0_0_0_0_0_0_0_0` pattern. (12 data symbols interleaved with 0s)
However, the inverse function truncates the very first `0_` pair, whatever the value of the input data.
This happens if the very first character does not represent input data, as the code does not enter the `if` statement.
This makes the `for` loop skip the first input sequence altogether.
I managed to solve this problem by inverting the two actions within the `for` loop (i.e. consume the carrier *first*).
Once all the input is consumed, the remaining carrier pattern is appended until it wraps around.
I hope you'll find this useful too! …
> 'Remove Carrier' encoding truncates initial input

- src/urh/controller/widgets/SignalFrame.py
- src/urh/signalprocessing/IQArray.py
- src/urh/signalprocessing/Signal.py
- src/urh/util/FileOperator.py
Add support for Flipper Zero .sub files
- Read
- Write (only if the source was a .sub file and with constant parameters)
Future work: Implement export to .sub files in Generator as a plugin (similar to YardStick that also uses CC1101) to support different parameters.
> Flipper raw

- src/urh/controller/CompareFrameController.py
- src/urh/dev/PCAPNG.py
- src/urh/signalprocessing/Message.py
- src/urh/signalprocessing/ProtocolAnalyzer.py
- src/urh/util/FileOperator.py
- tests/test_util.py
Now protocol analysis can be exported to PCAPNG format.
> Adding Save As pcapng for ProtocolAnalyzer

- src/urh/signalprocessing/Signal.py
For some reason, some of the files saved by Flipper Zero have a final white space. 
When the RAW_data line is splitted, the last white space gets its own `''` value in the array.
If we try to convert the `''` value to `int` we get an exception.
The exception has been controlled, showing a warning and skipping the value.
The line is stripped to remove white spaces before splitting.
> Fix .sub file RAW_data strip

- .github/workflows/ci.yml
PyAudio wheels for Windows are now provided on PyPi so we do not need to use pipwin anymore.
> CI: Install PyAudio directly via pip instead of pipwin

- src/urh/signalprocessing/IQArray.py
Fix errors like this:
```
[ERROR::SignalFrame.py::update_number_selected_samples] ndarray is not C-contiguous
Traceback (most recent call last):
File "/home/andy/work/repository/urh/src/urh/controller/widgets/SignalFrame.py", line 320, in update_number_selected_samples
power = np.mean(self.signal.iq_array.subarray(start, end, step_size).magnitudes_normalized)
File "/home/andy/work/repository/urh/src/urh/signalprocessing/IQArray.py", line 86, in magnitudes_normalized
return self.magnitudes / np.sqrt(self.maximum**2.0 + self.minimum**2.0)
File "/home/andy/work/repository/urh/src/urh/signalprocessing/IQArray.py", line 82, in magnitudes
return get_magnitudes(self.__data)
File "src/urh/cythonext/util.pyx", line 128, in urh.cythonext.util.__pyx_fuse_0get_magnitudes
File "stringsource", line …
```
> Fix error when selecting large ranges in Interpretation

- data/requirements.txt
- setup.py
Temporary measurement to bring the CI back to life. In perspective, we should make the Cython files compatible with version 3.0+.
> pin to Cython version <3.0.0

- .github/workflows/ci.yml
- LICENSE
- Update License year
- Use Python 3.11 for bundled Windows builds
- Use `windows-latest` for CI
> Update LICENSE and CI

- data/requirements.txt
- setup.py
- src/urh/dev/native/lib/sdrplay.pyx
> Add support for Cython3

- .github/workflows/black.yml
- .github/workflows/ci.yml
Solve the warning in workflow runs:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/setup-python@v4. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
> Update actions/setup-python to v5

- tests/awre/conftest.py
To prevent `fieldtypes.xml` not found for tests on macOS
> Add conftest.py to awre test dir

- setup.py
> Handle module __builtins__ both as dict or module

- src/urh/dev/native/lib/airspy.pyx
According to https://docs.python.org/3.13/whatsnew/3.13.html:
Remove PyEval_InitThreads() and PyEval_ThreadsInitialized() functions, deprecated in Python 3.9. Since Python 3.7, Py_Initialize() always creates the GIL: calling PyEval_InitThreads() did nothing and PyEval_ThreadsInitialized() always returned non-zero. (Contributed by Victor Stinner in https://github.com/python/cpython/issues/105182.)
If support for < python-3.7 is required, conditionals have to be added
> Fixed build with python-3.13

- data/requirements.txt
Python 3.12 dropped `distutils` from the standard library so we need `setuptools` to run URH. This fixes #1113.
> Add setuptools to requirements.txt

- .github/workflows/ci.yml
- data/requirements.txt
As suggested [here](https://github.com/jopohl/urh/issues/1123#issuecomment-2252712620) pin the numpy version to prevent errors with pipx.
This fixes #1144 and fixes #1122.
> Requirements: Pin to numpy 1.x.x

- .github/workflows/ci.yml
- README.md
- src/urh/awre/FormatFinder.py
- src/urh/dev/native/lib/limesdr.pyx
> Replace macos-12 with macos-13

- src/urh/cythonext/signal_functions.pyx
> Fixed gauss_fir to work with numpy-2

- .github/workflows/ci.yml
- data/requirements.txt
- setup.py
Building Limesuite on macOS currently fails with
```
Last 15 lines from /Users/runner/Library/Logs/Homebrew/limesuite/01.cmake:
-Wno-dev
-DBUILD_TESTING=OFF
-DCMAKE_OSX_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk
CMake Error at CMakeLists.txt:4 (cmake_minimum_required):
Compatibility with CMake < 3.5 has been removed from CMake.
Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
to tell CMake that the project requires at least <min> but has been updated
to work with policies introduced by <max> or earlier.
Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.
```
Unfortunately, homebrew does not respect `CMAKE_POLICY_VERSION_MINIMUM=3.5` when set via environment variable and there seems to be no way to specify cmake flags directly …
> [CI] Fix broken limesuite build for macOS

- src/urh/dev/native/RTLSDRTCP.py
This PR fixes #1121.
I have tested this with `rtl_tcp` and an RTL-SDR v3 dongle, plus a remote that sends unknown data on 315 MHz.
Both the recording and spectrogram look good; see screenshots.
Data recorded with RTL-TCP mode is now saved as `.complex16s` rather than `.complex16u` and the data can now be used for analysis.
> Fix receiving data with rtl_tcp

- src/urh/dev/native/RTLSDRTCP.py
The bias tee value was being set to the same value as the bandwidth.  In #1067 it was reported that the bias tee value was being set to the same value as the sample rate, but the sample rate and bandwidth are usually the same.
Urh's rtl_tcp driver never previously sent a bias tee command, but rtl_tcp was receiving one because at some point, the constants for bandwidth and bias tee got changed in the rtl_tcp implementation.  It appears that Osmocom's implementation always had the bias tee command at 0x0e; see https://gitea.osmocom.org/sdr/rtl-sdr/commit/fa3a113b77b6ed2738778a52ae4f9ce4e6f18ea3 when it was added.  However, the [pinkavaj fork](https://github.com/pinkavaj/rtl-sdr) initially had the bandwidth as 0x0e and bias tee as 0x0f.  See …
> Fix setting of bias tee with rtl_tcp

- src/urh/awre/Histogram.py
- src/urh/awre/engines/AddressEngine.py
- src/urh/signalprocessing/IQArray.py
- tests/awre/test_generated_protocols.py
- tests/test_send_recv_dialog_gui.py
Deprecated since numpy 1.19.0
https://numpy.org/doc/2.1/release/1.19.0-notes.html#numpy-ndarray-tostring-is-deprecated-in-favor-of-tobytes
Deprecations mentioned in #1149
> fix(numpy): replace deprecated `tostring` with `tobytes`

- .github/workflows/ci.yml
`pytest-faulthandler`: This plugin is now part of pytest core since pytest 5.0, so users should not install this plugin together with that pytest version.
`six`: Six is a Python 2 and 3 compatibility library.
> Remove outdated dependencies from CI

- src/urh/signalprocessing/Message.py
- src/urh/simulator/SimulatorConfiguration.py
- src/urh/util/ProjectManager.py
DeprecationWarning: Testing an element's truth value will always return True in future versions.  Use specific 'len(elem)' or 'elem is not None' test instead.
Changed in version 3.12: Testing the truth value of an Element emits DeprecationWarning.
https://docs.python.org/3.12/library/xml.etree.elementtree.html#xml.etree.ElementTree.Element
> Fix deprecation warning xml.etree.ElementTree.Element

- .github/workflows/black.yml
- .github/workflows/ci.yml
- setup.py
- src/urh/main.py
python 3.8 is EOL
python 3.8 is not supported by numpy2
Mentioned in https://github.com/jopohl/urh/issues/1149#issuecomment-2972767790
> Drop python 3.8; Require python 3.9

- data/requirements.txt
- setup.py
Make URH compatible with Ubuntu 24.04 again. Thank you for bringing this up!
fix #1179
> Revert numpy2 requirement
